name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/project-web-acas/lifeatykp-bri
            git pull origin main
            cp prisma/schema.prisma /var/lib/docker/volumes/project-web-acas_lifeatykp-db/_data/schema.prisma
            cd /home/project-web-acas
            docker compose up -d --build --force-recreate lifeatykp-bri